services:
  haproxy:
    image: haproxy:2.9-alpine
    container_name: travelltickets_haproxy
    user: "0:0"
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./haproxy/certs:/usr/local/etc/haproxy/certs:ro
    depends_on:
      - app
    security_opt:
      - no-new-privileges:true

  app:
    build: .
    container_name: travelltickets_app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "5000"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    extra_hosts:
      - "api.telegram.org:149.154.167.220"
    depends_on:
      - db
    security_opt:
      - no-new-privileges:true
    read_only: false

  db:
    image: postgres:16-alpine
    container_name: travelltickets_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    security_opt:
      - no-new-privileges:true

volumes:
  postgres_data:
